# Generated by Django 4.2.4 on 2023-08-31 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads_reports/",
                        validators=[reports.validators.validate_py_file],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("is_reported", models.BooleanField(default=False)),
                ("is_checked", models.BooleanField(default=False)),
                ("is_reloaded", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_file", models.FileField(null=True, upload_to="reports/")),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="reports.file",
                        verbose_name="файл",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pep8Warning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_code",
                    models.CharField(max_length=5, verbose_name="код статуса"),
                ),
                ("line", models.IntegerField(verbose_name="строка")),
                ("column", models.IntegerField(verbose_name="столбец")),
                ("message", models.CharField(max_length=255, verbose_name="сообщение")),
                (
                    "code_line",
                    models.CharField(max_length=510, verbose_name="строка кода"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pep8_warnings",
                        to="reports.report",
                        verbose_name="отчёт по pep8",
                    ),
                ),
            ],
        ),
    ]
