version: "3"
services:

  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./DockerfileWeb
    restart: always
    volumes:
      - static_value:/app/static/
      - data_value:/app/data/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static
      - data_value:/var/html/data
    depends_on:
      - web

  redis:
    restart: always
    image: redis
    env_file:
      - ./.env

  worker:
    restart: always
    build:
      context: ./
      dockerfile: ./DockerfileCelery
    volumes:
      - static_value:/app/static/
      - data_value:/app/data/
    depends_on:
      - redis
      - web
    env_file:
      - ./.env

#  beat_worker:
#    restart: always
#    build:
#      context: ./
#      dockerfile: ./DockerfileCeleryBeat
#    volumes:
#      - static_value:/app/static/
#      - data_value:/app/data/
#    depends_on:
#      - redis
#      - web
#    env_file:
#      - ./.env

volumes:
  static_value:
  data_value:
  db_value: