version: "3"
services:

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ../.env

  django:
    container_name: django
    build:
      context: ..
      dockerfile: ./infra/DockerfileDjango
    restart: always
    volumes:
      - static_value:/app/static/
      - data_value:/app/data/
    env_file:
      - ../.env
    depends_on:
      - postgresql

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ../infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static
      - data_value:/var/html/data
    depends_on:
      - django

  redis:
    restart: always
    image: redis
    env_file:
      - ../.env

  celery:
    restart: always
    build:
      context: ..
      dockerfile: ./infra/DockerfileCelery
    volumes:
      - static_value:/app/static/
      - data_value:/app/data/
    depends_on:
      - redis
      - django
    env_file:
      - ../.env

volumes:
  static_value:
  data_value:
  db_value: